# Generated by Django 2.1.5 on 2019-03-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
